{{- $namespace := .Release.namespace }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap }}
  namespace: {{ $namespace }}
data:
  CLOUD_PROVIDER: az
  OPENAPI_PREFIX: /api/os-well-delivery-ddms
  SERVICE_HOST_STORAGE: http://storage.{{ .Values.coreServicesNamepsace }}/api/storage
  SERVICE_HOST_SEARCH: http://search-service.{{ .Values.coreServicesNamepsace }}/api/search
  SERVICE_HOST_PARTITION: http://partition.{{ .Values.coreServicesNamepsace }}/api/partition
  USE_PARTITION_SERVICE: enabled
  AZ_LOGGER_LEVEL: INFO

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: osdu-svc-config
  namespace: {{ $namespace }}
data:
  ENV_KEYVAULT: https://{{ .Values.azure.keyvault }}.vault.azure.net/
  REDIS_DB_AIRFLOW: "1"
  REDIS_DB_PARTITION: "2"
  REDIS_DB_ENTITLEMENTS: "3"
  REDIS_DB_LEGAL: "4"
  REDIS_DB_STORAGE: "5"
  REDIS_DB_INDEXER: "6"
  REDIS_DB_SEARCH: "7"
  REDIS_DB_DELIVERY: "8"
  REDIS_DB_FILE: "9"
  REDIS_DB_SDMS: "10"
