nodepoolNamePrefix: <nodepool_name_prefix>
dataPartitions: <dataPartition_names>
resources:
  limits:
    cpu: 2
    memory: 8
  requests:
    cpu: 0.2
elasticsearch:
  version: 7.16.3
  nodeCount: 3
  storagePerNodeGB: 128
