nodepoolNamePrefix: <nodepool_name_prefix>
dataPartitions: <dataPartition_names>
primaryUserName: <primary_user_name>
secondaryUserName: <secondary_user_name>
userJobName: <user_job_name>
licenseType: <license_type>
licenseValue: <license_value>
resources:
  limits:
    cpu: 2
    memory: 8
  requests:
    cpu: 0.2
elasticsearch:
  version: 7.16.3
  nodeCount: 3
  storagePerNodeGB: 128
