{{- $namespace := .Release.Namespace }}
{{- $pullPolicy := .Values.global.pullPolicy -}}
{{- $servicePort := .Values.global.service.port -}}
{{- $replicaCount := .Values.global.replicaCount -}}
{{- $isAutoscalingEnabled := .Values.global.isAutoscalingEnabled}}
{{- $nodepool := .Values.global.nodepool}}
{{- $defaultNodepool := .Values.global.defaultNodepool }}
{{- $version := .Chart.AppVersion -}}
{{- $release := .Release.Name }}
{{- $podIdentityAuthEnabled := .Values.global.azure.podIdentityAuthEnabled}}
{{- $isHpaEnabled := .Values.global.autoscale.enabled}}
{{- range .Values.configuration }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .service }}
  namespace: {{ $namespace }}
spec:
{{- if not $isHpaEnabled }}
  replicas: {{ .replicaCount | default $replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ .service }}
  template:
    metadata:
      labels:
        app: {{ .service }}
        aadpodidbinding: osdu-identity
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
    spec:
{{- if $isAutoscalingEnabled }}
      nodeSelector:
        agentpool: {{ $nodepool }}
{{- else if $defaultNodepool }}
      nodeSelector:
        agentpool: {{ $defaultNodepool }}
{{- end }}
      volumes:
      {{- if .keyvault }}
        - name: azure-keyvault
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-keyvault
      {{- end }}
      {{- range .pvc }}
        - name: {{ .volume }}
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
      {{- end }}
      containers:
        - name: {{ .service }}
          {{- if hasPrefix "<azure_acr>/" .repository }}
          {{- $repo := .repository | replace "<azure_acr>/" "msosdu.azurecr.io/" }}
          image: {{ $repo }}:{{ .tag | default $version }}
          {{- else }}
          image: {{ .repository }}:{{ .tag | default $version }}
          {{- end }}
          imagePullPolicy: {{ $pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: {{ $servicePort }}
              protocol: TCP
          {{- if .probe }}
          readinessProbe:
            httpGet:
              path: {{ .probe }}
              port: http
            initialDelaySeconds: 20
          {{- end }}
          resources:
          {{- if .request }}
            requests:
              cpu: {{ .request.cpu | quote }}
          {{- end }}
          {{- if .limit }}
            limits:
              cpu: {{ .limit.cpu | quote }}
          {{- end }}
          volumeMounts:
          {{- if .keyvault }}
          - name: azure-keyvault
            mountPath: "/mnt/azure-keyvault"
            readOnly: true
          {{- end }}
          {{- range .mount }}
          - name: {{ .name }}
            mountPath: {{ .path }}
          {{- end }}
          {{- if .env }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              {{- if .value }}
              { { - $v := .value } }
              value: { { tpl ($v | quote) $ } }
              {{- end }}
              {{- if .config }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .config.name }}
                  key: {{ .config.key | quote }}
              {{- end }}
              {{- if .secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret.name | quote }}
                  key: {{ .secret.key | quote }}
              {{- end }}
            {{- end }}
            {{- if not $podIdentityAuthEnabled }}
            {{- range .podIdentityEnvs }}
            - name: {{ .name }}
              {{- if .secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret.name | quote }}
                  key: {{ .secret.key | quote }}
              {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}

---
{{- end }}
