#We are creating a config map in default namespace . This config map has key as a flag "elastic_pwd_changed" which will be set to true when password for es primary and secondary user for any data partition is changed and consuming services need to restart 
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: es-primary-secondary-user-pwd-changed-flag
  namespace: osdu-azure 
data:
  elastic_pwd_changed: | 
    1
