# This file contains the essential configs for the Azure Data Initialization Agent
################################################################################
# Specify the azure environment specific values
#
azure:
  resourcegroup: <azure_resourcegroup>
  identity_id: <azure_identity_id>
  appid: <azure_appid> # can be an AAD App OID or a user email

service:
  domain: <service_domain> # eg: contoso.com

ingress:
  dns: <ingress_dns>

storage:
  partitions: <storage_partitions> #A comma separated(no space) list of partition names

config:
  configmapname: ~~CONFIG_MAP_NAME~~

image:
  repository: msosdu.azurecr.io
  tag: <image_tag>