# This file contains the essential configs for the Azure Data Seeding Agent
################################################################################
# Specify the azure environment specific values
#
azure:
  tenant: <tenant>
  subscription: <subscription>
  resourcegroup: <resourcegroupp>
  identity: <identity>
  identity_id: <identity_id>
  keyvault: <keyvault>
  appid: <aad client/app id> # can be an AAD App OID or a user email

storage:
  partitions: <partitions> #A comma separated(no space) list of partition names

config:
  configmapname: ~~CONFIG_MAP_NAME~~

image:
  repository: msosdu.azurecr.io
  tag: <version>
